require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe Admin::MonaArticlesController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # MonaArticle. As you add validations to MonaArticle, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # Admin::MonaArticlesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all mona_articles as @mona_articles" do
      mona_article = MonaArticle.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:mona_articles)).to eq([mona_article])
    end
  end

  describe "GET #show" do
    it "assigns the requested admin_mona_article as @admin_mona_article" do
      mona_article = MonaArticle.create! valid_attributes
      get :show, {:id => mona_article.to_param}, valid_session
      expect(assigns(:admin_mona_article)).to eq(mona_article)
    end
  end

  describe "GET #new" do
    it "assigns a new admin_mona_article as @admin_mona_article" do
      get :new, {}, valid_session
      expect(assigns(:admin_mona_article)).to be_a_new(MonaArticle)
    end
  end

  describe "GET #edit" do
    it "assigns the requested admin_mona_article as @admin_mona_article" do
      mona_article = MonaArticle.create! valid_attributes
      get :edit, {:id => mona_article.to_param}, valid_session
      expect(assigns(:admin_mona_article)).to eq(mona_article)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new MonaArticle" do
        expect {
          post :create, {:admin_mona_article => valid_attributes}, valid_session
        }.to change(MonaArticle, :count).by(1)
      end

      it "assigns a newly created admin_mona_article as @admin_mona_article" do
        post :create, {:admin_mona_article => valid_attributes}, valid_session
        expect(assigns(:admin_mona_article)).to be_a(MonaArticle)
        expect(assigns(:admin_mona_article)).to be_persisted
      end

      it "redirects to the created admin_mona_article" do
        post :create, {:admin_mona_article => valid_attributes}, valid_session
        expect(response).to redirect_to(MonaArticle.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved admin_mona_article as @admin_mona_article" do
        post :create, {:admin_mona_article => invalid_attributes}, valid_session
        expect(assigns(:admin_mona_article)).to be_a_new(MonaArticle)
      end

      it "re-renders the 'new' template" do
        post :create, {:admin_mona_article => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested admin_mona_article" do
        mona_article = MonaArticle.create! valid_attributes
        put :update, {:id => mona_article.to_param, :admin_mona_article => new_attributes}, valid_session
        mona_article.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested admin_mona_article as @admin_mona_article" do
        mona_article = MonaArticle.create! valid_attributes
        put :update, {:id => mona_article.to_param, :admin_mona_article => valid_attributes}, valid_session
        expect(assigns(:admin_mona_article)).to eq(mona_article)
      end

      it "redirects to the admin_mona_article" do
        mona_article = MonaArticle.create! valid_attributes
        put :update, {:id => mona_article.to_param, :admin_mona_article => valid_attributes}, valid_session
        expect(response).to redirect_to(mona_article)
      end
    end

    context "with invalid params" do
      it "assigns the admin_mona_article as @admin_mona_article" do
        mona_article = MonaArticle.create! valid_attributes
        put :update, {:id => mona_article.to_param, :admin_mona_article => invalid_attributes}, valid_session
        expect(assigns(:admin_mona_article)).to eq(mona_article)
      end

      it "re-renders the 'edit' template" do
        mona_article = MonaArticle.create! valid_attributes
        put :update, {:id => mona_article.to_param, :admin_mona_article => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested admin_mona_article" do
      mona_article = MonaArticle.create! valid_attributes
      expect {
        delete :destroy, {:id => mona_article.to_param}, valid_session
      }.to change(MonaArticle, :count).by(-1)
    end

    it "redirects to the mona_articles list" do
      mona_article = MonaArticle.create! valid_attributes
      delete :destroy, {:id => mona_article.to_param}, valid_session
      expect(response).to redirect_to(mona_articles_url)
    end
  end

end
